Practica3.EF/Practica3.EF.MVC/Models/BreakingBadQuoteModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Practica3.EF.MVC.Models
{
    public class BreakingBadQuoteModel
    {
        public string Quote { get; set; }
        public string Author { get; set;}
    }
}

Practica3.EF/Practica3.EF.MVC/Models/BreakingBadService.cs
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using System.Web;

namespace Practica3.EF.MVC.Models
{
    public class BreakingBadService
    {
        private readonly WebClient _webClient;

        public BreakingBadService()
        {
            _webClient = new WebClient();
            _webClient.BaseAddress = "https://api.breakingbadquotes.xyz/v1/";
        }


        public List<BreakingBadQuoteModel> GetRandomQuotes(int count)
        {
            List<BreakingBadQuoteModel> quotes = new List<BreakingBadQuoteModel>();

            for (int i = 0; i < count; i++)
            {
                string responseContent = _webClient.DownloadString("quotes");
                BreakingBadQuoteModel quote = JsonConvert.DeserializeObject<List<BreakingBadQuoteModel>>(responseContent)[0];

                quotes.Add(quote);
            }

            return quotes;
        }
    }
}

Practica3.EF/Practica3.EF.MVC/Models/ShipperViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Practica3.EF.MVC.Models
{
    public class ShipperViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string  Phone { get; set; }
    }
}

Practica3.EF/Practica3.EF.MVC/Controllers/BreakingBadController.cs
using Practica3.EF.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Practica3.EF.MVC.Controllers
{
    public class BreakingBadController : Controller
    {
        // GET: BreakingBad
        private readonly BreakingBadService _breakingBadService;

        public BreakingBadController()
        {
            _breakingBadService = new BreakingBadService();
        }

        public ActionResult Index()
        {
            List<BreakingBadQuoteModel> quotes = _breakingBadService.GetRandomQuotes(3);
            return View(quotes);
        }
    }
}

Practica3.EF/Practica3.EF.MVC/Controllers/HomeController.cs
using Practica3.EF.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practica3.EF.MVC.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Leandro Burbano";

            return View();
        }
    }
}

Practica3.EF/Practica3.EF.MVC/Controllers/ShipperController.cs
using Practica3.EF.Entities;
using Practica3.EF.Logic;
using Practica3.EF.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practica3.EF.MVC.Controllers
{
    public class ShipperController : Controller
    {
        // GET: Shipper
        public ActionResult Index()
        {
            ShipperLogic shipperLogic = new ShipperLogic();
            List<ShipperViewModel> result = shipperLogic.GetAll().Select(s => new ShipperViewModel { Id = s.ShipperID, Name = s.CompanyName, Phone = s.Phone}).ToList();
            return View(result);
        }

        public ActionResult Eliminar(int id)
        {
            ShipperLogic shipperLogic = new ShipperLogic();
            shipperLogic.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult Actualizar(int id) 
        {
            ShipperLogic shipperLogic = new ShipperLogic();
            ShipperViewModel model = new ShipperViewModel();
            Shippers ship = shipperLogic.GetById(id);
            var shipper = ship;
            model.Id = shipper.ShipperID;
            model.Name = shipper.CompanyName;
            model.Phone = shipper.Phone;

            return View(model);
        }

        [HttpPost]
        public ActionResult Actualizar(ShipperViewModel model)
        {
            Shippers shipper = (new Shippers { ShipperID = model.Id, CompanyName = model.Name, Phone = model.Phone });
            ShipperLogic shipperLogic = new ShipperLogic();
            shipperLogic.Update(shipper);

            return RedirectToAction("Index");
        }

        public ActionResult Crear(Shippers shipper)
        {
            var ship = new Shippers();
            ShipperViewModel model = new ShipperViewModel();
            
            model.Name = ship.CompanyName;
            model.Phone = ship.Phone;


            return View(model);
        }

        [HttpPost]
        public ActionResult Crear(ShipperViewModel model)
        {
            Shippers shipper = (new Shippers { CompanyName = model.Name, Phone = model.Phone });
            ShipperLogic shipperLogic = new ShipperLogic();

            shipperLogic.Add(shipper);

            return RedirectToAction("Index");
        }
    }
}

Practica3.EF/Practica3.EF.MVC/Views/BreakingBad/Index.cshtml
@model List<Practica3.EF.MVC.Models.BreakingBadQuoteModel>
@{
    ViewBag.Title = "Index";
}

<div class="fullcontainer">
    

        <h2 class="display-4 text-center text-secondary titulo">Frases de Breaking Bad</h2>
    
    <div class="frases container" >

 @foreach (var quote in Model)
    {
        <div class="card">
            <div class="card-header">
                Frase
            </div>
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p>@quote.Quote</p>
                    <footer class="blockquote-footer"><cite title="Source Title">@quote.Author</cite></footer>
                </blockquote>
            </div>
        </div>
    }
    </div>
    
</div>

Practica3.EF/Practica3.EF.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Practica3.EF/Practica3.EF.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<div class="d-flex flex-column mt-5 ">

<h2 class="text-center">Realizado por: </h2>
<h3 class="text-center">@ViewBag.Message</h3>


<address class="text-center">
    <strong>Web:</strong>   <a href="https://lburbano.site/">Clic Aquí</a><br />
</address>
</div>

Practica3.EF/Practica3.EF.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron hero">
    <div class="insidej">
        <h1 class="display-1 titulo">Bienvenido a Frases de Breaking Bad!</h1>
        <div class="d-flex justify-content-center">

        <p><a class="btn btn-primary btn-lg cta" href="/BreakingBad" role="button">Conoce mas &#9193;</a></p>
        </div>
    </div>
</div>

Practica3.EF/Practica3.EF.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html >
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consumo API</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body class="h-100">
    <nav class="navbar navbar-expand-lg text navbar-dark bg-dark">
        <a class="navbar-brand"> @Html.ActionLink("TP-7", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">@Html.ActionLink("Inicio", "Index", "Home", new { }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Shippers", "Index", "Shipper", new { }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Frases", "Index", "BreakingBad", new { }, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Contacto", "Contact", "Home", new { }, new { @class = "nav-link" })</li>
            </ul>
        </div>
    </nav>
    <div>
        @RenderBody()
        <hr />
        <footer class="footer text-center bg-dark text-white pt-3 pb-2 mt-auto">
            <p>Leandro Burbano &copy; @DateTime.Now.Year - Lab .Net TP-7 Consumo API Externa </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Shipper")
    @RenderSection("scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</body>
</html>

Practica3.EF/Practica3.EF.MVC/Views/Shipper/Actualizar.cshtml
@model Practica3.EF.MVC.Models.ShipperViewModel
@{
    ViewBag.Title = "Actualizar";
}

<div class="container d-flex justify-content-between">
    <h2 class="mt-3 display-4 ">Actualizar</h2>
    <div class="d-flex align-items-center">
       
        <a class="btn btn-outline-secondary" href="/Shipper">Regresar</a>
    </div>
</div>
<div class="container">
        <div class="d-flex justify-content-center align-content-center">
            <form method="post" id="factualizar" onsubmit="factualizar(event)">
                <div class="form-group">
                    <div class="form-group">

                        <label for="Name">Nombre</label>
                        <input class="form-control" required id="Name" name="Name" type="text" value="@Model.Name" />
                    </div>
                    <div class="form-group">

                        <label for="Phone">Telefono</label>
                        <input class="form-control" required id="Phone" name="Phone" type="text" value="@Model.Phone" />
                    </div>
                    <div class="form-group">

                        <button class="btn btn-outline-success" type="submit">Actualizar</button>
                    </div>
                </div>
            </form>
            </div>
           
        </div>

Practica3.EF/Practica3.EF.MVC/Views/Shipper/Crear.cshtml
@model Practica3.EF.MVC.Models.ShipperViewModel

@{
    ViewBag.Title = "Crear";
}

<div class="container d-flex justify-content-between">
    <h2 class="mt-3 display-4 ">Crear</h2>
    <div class="d-flex align-items-center">

        <a class="btn btn-outline-secondary" href="/Shipper">Regresar</a>
    </div>
</div>
<div class="container">
    <div class="d-flex justify-content-center align-content-center">
        <form method="post" id="fagregar" onsubmit="fagregar(event)">
            <div class="form-group">
                <div class="form-group">

                    <label for="Name">Nombre</label>
                    <input class="form-control" id="Name" required name="Name" type="text" value="@Model.Name" />
                </div>
                <div class="form-group">

                    <label for="Phone">Telefono</label>
                    <input class="form-control" id="Phone" required name="Phone" type="text" value="@Model.Phone" />
                </div>
                <div class="form-group">

                    <button class="btn btn-outline-success" type="submit">Crear</button>
                </div>
            </div>
        </form>
    </div>

</div>

Practica3.EF/Practica3.EF.MVC/Views/Shipper/Index.cshtml
@model List<Practica3.EF.MVC.Models.ShipperViewModel>
@{
    ViewBag.Title = "Index";
}

<div class="container-fluid">

    <div class="d-flex justify-content-between"> 
        <h2 class="mt-3 display-4 ">Shippers</h2>
        <div class="d-flex align-items-center">
            <p class="align-middle lead m-0">Crear &nbsp;</p>

            @Html.ActionLink(" ", "Crear", new { }, new { @class = "btn btn-outline-primary p-3 fa-solid fa-user-plus" })

        </div>
    </div>

    <table class="table table-striped mt-5">
        <thead>
            <tr>
                <td>Id</td>
                <td>Nombre</td>
                <td>Telefono</td>
                <td>Editar</td>
                <td>Eliminar</td>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Phone
                    </td>
                    <td>
                        @Html.ActionLink(" ", "Actualizar", new { id = item.Id }, new { @class = "btn btn-outline-success fa-sharp fa-solid fa-pen-to-square" })

                    </td>
                    <td>
                        @Html.ActionLink(" ", "Eliminar", new { id = item.Id }, new
                   {
                       onclick = "return confirm('¿Está seguro de que desea eliminar este registro?')",
                       @class = "btn btn-outline-danger fa-solid fa-trash-can"
                   })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="modal fade" id="modalShipper" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/Shipper.js"></script>